# Generated by Django 4.0.3 on 2022-03-21 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box_plans', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='box_plan_category',
        ),
        migrations.AddField(
            model_name='customer',
            name='box_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box_plans.box_plan'),
        ),
        migrations.AddField(
            model_name='customer',
            name='self_teach_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box_plans.self_teach_plan'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_beginner_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box_plans.total_beginner_package'),
        ),
    ]
