# Generated by Django 4.0.3 on 2022-03-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_card_payment',
            name='cc_cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='credit_card_payment',
            name='cc_number',
            field=models.IntegerField(),
        ),
    ]
