# Generated by Django 4.0.3 on 2022-03-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card_payments', '0002_alter_credit_card_payment_cc_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_card_payment',
            name='cc_cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='credit_card_payment',
            name='cc_number',
            field=models.CharField(max_length=16),
        ),
    ]
