# Generated by Django 4.0.3 on 2022-03-22 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_card_payments', '0003_alter_credit_card_payment_cc_cvv_and_more'),
        ('customers', '0002_remove_customer_box_plan_category_customer_box_plan_and_more'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('is_paid', models.BooleanField()),
                ('credit_card_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_card_payments.credit_card_payment')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.shipping')),
            ],
        ),
    ]
