# Generated by Django 4.0.3 on 2022-03-21 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('box_plans', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_type', models.CharField(max_length=30)),
                ('shipping_company', models.CharField(max_length=30)),
                ('shipping_cost', models.IntegerField()),
                ('box_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box_plans.box_plan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('total_beginner_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box_plans.total_beginner_package')),
            ],
        ),
    ]
