# Generated by Django 4.0.3 on 2022-03-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box_plans', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='box_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box_plans.box_plan'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='total_beginner_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box_plans.total_beginner_package'),
        ),
    ]
